sudo: true

language: scala
jdk:
  - oraclejdk8

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

services:
  - docker

install:
  - wget https://www.foundationdb.org/downloads/6.0.15/ubuntu/installers/foundationdb-clients_6.0.15-1_amd64.deb
  - sudo dpkg -i foundationdb-clients_6.0.15-1_amd64.deb

jobs:
  include:
    - stage: test
      script: sbt compile coverage test coverageReport coverageAggregate codacyCoverage clean
    - stage: release
      script: sbt ci-release

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

before_install:
  - git fetch --tags

env:
  global:
  - secure: Hxs45SdnHn7FJvRVLNsKTIzx7AHM9ky7pHIWkYQLkfELtBsjVYyUmuFzfc6IIanJXjRNdB9mBr63BZZbdSD6AJNMlxJaglki3y1jx3aIHO8u5SX9c/+l0p6iRJEvNAqrWjcP/HKkPU/WyrndwBzgnjua8QItIfyG7v2dBJKaKqbCnee+pavwhcxh9r4v4NyVXHL0gcCqppGUG8/1AOlV4XzpVjjtH54ANRNErW4KpBKap0QAF4roEmz1r7GqnK5Lgk5SeWQ5JoVZHjSxmgmXmrLXfg+wwQ1FdFcHWvfsJv3NnLIHIzY0Ej+SHsBYuvzRNjIc4lXl2yT/Yapto2/8uIqwYtWs+x/XH/uxUZQZSdDNimTyyXgD49bAA6t69k377EaSJ6p0RM7E0yw2l0gXcvi7qwiBleZLLawUBqZI3MEh5YDv5O4pgJTKrevm9XCGutVJWUZ8HNt9F/oMJtmuzhKzAE2heGuZf39rd4QlC5hTdgDq+WgUt1o8P33FjNmVgWsmr6r7Rt/XNkudBRt+NVUCPHZ0qfMFCPpJvoGJEUMdrf9TtrbavCODj8PeyudaM+nDFIybcx1AYJF0znM/qjbdEooHMIeqSxvdKBoAVQDgdX5SqlUtEQaML1XYrblWyvOuEN73gRKhWkdUsDa0mztdaczr8PhrUyrwVSl4648=
  - secure: J1b/rZ+tJCLp1QHhKjSEXqHYH5K4eI8mTkGyjVjdH0jy3pZC6lC4oUocXSkdSjJ8nyj6vKTzvxto5r7QvGEpB5IpIih9E8eGFxVsWnEVc6KI38DzxXBaQLxPJzCDo0/M0VfobxyIcJwhFe5EfV8LM/qkllltnxDk2K3wt3DVDJj7FJFjto+ca3uQjvW+Ty58pDEZxcHr4rZ8Z3JLenKMtb3ScnYpHcIH9YLI9g0sZ15y/X6MWwNNFdd8lVtUc/yfv1ZJk2h7YM+Pkvgn47wZ+Axq2519rAmpOGxeosjj5k2RGXSTFRLVgP/6r3OHULc9PuM6rKIlVC0lL5jfnAzU7GgdDVH+PPQTMz3xXHHJQrzrc0usnUTmii5NAY21OOOzh/027uIAyDdK0hab40Tcx6dUCFBEwxnq15p/U+IOMaPL9AnyB3GSJCGABv8raa5q6mfQ8CDFf1grDZiOVUrKTbPjTup2m0/08OSmldvsadr2TatW+UImqGTSLHG4nESm/EqebTelXzdpfETfzP3xzsY004pJ+js/1YjtPeEzN/A1bYa8CDP1QBDGBfnntaLBuzGDpD5Sv9OdPYXRzuT0D+tX1xT78PeKLrjph1g1LuopV93z+NBKupe8njTGJT016fD4tuhrCSxelleheYBoh77mEnQYm2apZ6Hq2U5ZUcU=
  - secure: HQcn04M0W6ckKDNMAepkvJrIPbr/stXRzHHM4rdgtcQLB05GTeWrpy96LBGgN0Gmh4cUV5mQz3uZkiiRf6FqD0ttgVMiad/5Phwndn4tE8NeUgjynCciRm3agajFa+RRUT9aSqO18lo71tc13Nw4xZU8j8jlozhLi/LtUwzwW/ox8BMAXOkB1vPAQ1X8gh2kSkdN4p8j4YlfYneVZw22oqRz78BBYyH8Urx89nLEY1Wrpwgf3s6kwTmvBblt/yfYxdS9dNdO31uyOoHBiVkDLtU1k2pJ3ACvZXZW9TMQVdA8Nc/5o6Hn1tn0ibrLN/EpfrTQaJITSPDi2mgN41zOum6YdDNa0OtxwjcNyDh2Fs0tDfhOaxgYED49wUoawX4f1fG2vXnXzNGsmsrXpyzejxnPCW6xSkKdVKfaHagSdKpLhAvEUKO9pfBKKa/wvYBL3wHQBUU0bmclpoGCzejCxx/VJ9Kd+d4veqHmUODGqq5yzmO4xno9N4mUB0M16zFDqXGDyEulf7a5RYEafWo1UTiOM5DPSfJkRoL81aXyXojvEIDQ7pX/M8xYFxOm9z1A9USNzixzJuuPJzL7h8e9L7GmSDRFMpMsfebqlFAA2F6jGnsJrLKYbGiXDaLTqp1c+YJgYjDq4kWccDPb0PVWa0xdrX5QQHHmRZrNVDFfmKM=
