sudo: true
branches:
  only:
  - master
services:
- docker
language: scala
scala:
- 2.12.7
install:
- wget https://www.foundationdb.org/downloads/6.0.15/ubuntu/installers/foundationdb-clients_6.0.15-1_amd64.deb
- sudo dpkg -i foundationdb-clients_6.0.15-1_amd64.deb
jdk:
- openjdk8
script:
- sbt clean coverage test
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
after_success:
- sbt coverageReport coverageAggregate codacyCoverage
- sbt clean compile +publish
env:
  global:
  - secure: Hxs45SdnHn7FJvRVLNsKTIzx7AHM9ky7pHIWkYQLkfELtBsjVYyUmuFzfc6IIanJXjRNdB9mBr63BZZbdSD6AJNMlxJaglki3y1jx3aIHO8u5SX9c/+l0p6iRJEvNAqrWjcP/HKkPU/WyrndwBzgnjua8QItIfyG7v2dBJKaKqbCnee+pavwhcxh9r4v4NyVXHL0gcCqppGUG8/1AOlV4XzpVjjtH54ANRNErW4KpBKap0QAF4roEmz1r7GqnK5Lgk5SeWQ5JoVZHjSxmgmXmrLXfg+wwQ1FdFcHWvfsJv3NnLIHIzY0Ej+SHsBYuvzRNjIc4lXl2yT/Yapto2/8uIqwYtWs+x/XH/uxUZQZSdDNimTyyXgD49bAA6t69k377EaSJ6p0RM7E0yw2l0gXcvi7qwiBleZLLawUBqZI3MEh5YDv5O4pgJTKrevm9XCGutVJWUZ8HNt9F/oMJtmuzhKzAE2heGuZf39rd4QlC5hTdgDq+WgUt1o8P33FjNmVgWsmr6r7Rt/XNkudBRt+NVUCPHZ0qfMFCPpJvoGJEUMdrf9TtrbavCODj8PeyudaM+nDFIybcx1AYJF0znM/qjbdEooHMIeqSxvdKBoAVQDgdX5SqlUtEQaML1XYrblWyvOuEN73gRKhWkdUsDa0mztdaczr8PhrUyrwVSl4648=
  - secure: J1b/rZ+tJCLp1QHhKjSEXqHYH5K4eI8mTkGyjVjdH0jy3pZC6lC4oUocXSkdSjJ8nyj6vKTzvxto5r7QvGEpB5IpIih9E8eGFxVsWnEVc6KI38DzxXBaQLxPJzCDo0/M0VfobxyIcJwhFe5EfV8LM/qkllltnxDk2K3wt3DVDJj7FJFjto+ca3uQjvW+Ty58pDEZxcHr4rZ8Z3JLenKMtb3ScnYpHcIH9YLI9g0sZ15y/X6MWwNNFdd8lVtUc/yfv1ZJk2h7YM+Pkvgn47wZ+Axq2519rAmpOGxeosjj5k2RGXSTFRLVgP/6r3OHULc9PuM6rKIlVC0lL5jfnAzU7GgdDVH+PPQTMz3xXHHJQrzrc0usnUTmii5NAY21OOOzh/027uIAyDdK0hab40Tcx6dUCFBEwxnq15p/U+IOMaPL9AnyB3GSJCGABv8raa5q6mfQ8CDFf1grDZiOVUrKTbPjTup2m0/08OSmldvsadr2TatW+UImqGTSLHG4nESm/EqebTelXzdpfETfzP3xzsY004pJ+js/1YjtPeEzN/A1bYa8CDP1QBDGBfnntaLBuzGDpD5Sv9OdPYXRzuT0D+tX1xT78PeKLrjph1g1LuopV93z+NBKupe8njTGJT016fD4tuhrCSxelleheYBoh77mEnQYm2apZ6Hq2U5ZUcU=
  - secure: YMQ8Fz9raBFocNQ74sd6IxqSLfkJh89JaFXJrFwqbgexU2B/BMiQAd1jlBIi2L8XZ9SzpSf8lj6f2sBoHS3qZv7GPS3T/31b5rPgxpltknhgOPoOVh/GIagnGEzmroRYs9KmH6G48dvXIyOTfmRYwOjhy5dcoUK9QEDDxpCxL6TXdqrFJ6P/+vYpNmcZ9YNfiTQbbepXfZ9Xdd/bM8e6xLsaSzomHvNTRCuC6A2KLjwBhbedoSTMgNqTlgHOCDFU519LPg6o6Aki5hfiFsy2C2012z0Q8L45tPiov/YxELwdtHuOUHXVV0PQ91p/GazKm/qabCGV4gjV2JLW+ezE8ladNaU5db35u2zQT6TgpwKJE/s7rJkLzI/8qeTNoE1M1fUnguG5+i5IgHnU2RDe8brgtchqRhUGr1VgK4ZjoAAr0M2fz7s/xZldjjmyqnrDIni+p42PU6rOuhIiNusdCDbSfNMKJcS6pxqmLHYe9Ofqpcj6ixcqL7Lym+GNzr5zTHExIqKq46cGLx+IqrR8cHQlYhnWQEKRHaWgnbOkatOlERHYmWAHWIkWz0bfeS53BMcrP3LrleJiocMWgoJNSGswRB/38Ew+/RzHvN8lXvQiBrTpyPkVlxeNtSTiSfetHxfUDRMgZkRDUPoLj50Y3vl3FkDBlV9eo4I7MnxXW7g=
